export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_ERRORS = "SET_ERRORS";
export const FETCH_RECIPES = "FETCH_RECIPES";
export const FETCH_RECIPE_DETAIL = "FETCH_RECIPE_DETAIL";
export const SET_PROFILE = "SET_PROFILE";
export const EDIT_PROFILE = "EDIT_PROFILE";
export const RESET_PROFILE = "RESET_PROFILE";
export const FETCH_INGREDIANTS = "FETCH_INGREDIANTS";
